// Tests the distribution generated by Java's Math.random() function.
//שאלה 2
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int n = Integer.parseInt(args[0]);
		int counter1 = 0;
		int counter2 = 0;
		double ratio;
		
		for (int i = 0; i < n ; i ++){

			double a = (Math.random());
			if (a > 0.5){
				counter1 ++;
			}
			else {
				counter2 ++;
			}
		}
		
		System.out.println("> 0.5:  "  + counter1 + " times");
		System.out.println("<= 0.5: "  + counter2 + " times");

		if (counter1 != 0 && counter2 != 0 ){
			if (counter1 < counter2){
			ratio = (double)counter1 /(double)counter2;
			System.out.println("Ratio:   " + ratio);
		}	
			else {
			ratio = (double)counter2 / (double)counter1;
			System.out.println("Ratio:   " + ratio);
		}
		}
		 
	}
}
